"""Generated by tools/gen_setup_payload.py -- do not edit by hand.

Everything the Setup button needs to build a gateway from nothing. Payloads are
zlib-compressed and base64-encoded; call the accessor rather than touching the blobs.
"""
import base64
import json
import zlib


def _blob(b64):
    return zlib.decompress(base64.b64decode(b64))


def _json(b64):
    return json.loads(_blob(b64))

_PROVIDER = (
    "eNqdj7GOAjEMRP/FNV9At2ibEydAQIcozO4ERWcSFDugFdp/P+cK+qOzxn4z4xfdSw5RQMsXsUh+rnj4cUFoGVgUC0Lii+DI"
    "1z0CCtKAg+XigJXqa5vuPtPh2G36bt/TvCCFWUxXbZ4jAlexno011zJgw7d2v959kXuP0XYot6gac/oDFEMt0aZvPCCunM7v"
    "jE5kG1pAAY/bJNO7YxM+8HmwVDinUa095rtW9MIKL/d0HP92nedfIt94WA=="
)


def tagProvider():
    return _json(_PROVIDER)


_HISTORIAN = (
    "eNpNjsEKwjAMht8l5x7Ug4fdPAgTmYpTxGO2ZRKsbW0zRMfe3daheEr48pP/68F527ImyHqQp4sTyrvOOYj1jAYGBYFE2FxC"
    "ijQoWGFIsfVuBQocemFha9KVDFaaGsjEd6TAOuEbvxJoUYd/cmLT2EdJtTVNfDyfxJrIIZuOy9GwRA7FdnPIk4TznYkSqQUv"
    "Yy7Ob+y8XOyjzK//U5fUBTUVnRZ2mslDNlMgHutrWdNoOQxvb+NY3A=="
)


def historian():
    return _json(_HISTORIAN)


_DEVICE = (
    "eNoVi7EKwzAMBf9FcwZ3zdylQ6EkX6CmL0Ygx0ZWAiH43+NOx8HdRcXyKgoaL/KzdNLHcjROib+KWdKu7NmeOGQBtYEq3GWL"
    "9X8oIi/nO//6t7JWDGQoYKfRbe/mkvDaHHawTuw9e4QQWrsBXDcrOQ=="
)


def device():
    return _json(_DEVICE)


_INSTRUCTIONS = (
    "eNqtV8tu2zAQvPcrBJ9SQKDF5UPSMY8CDVqgRmK06FGxmVaoLRmUlMB/35VoNwxi0lSji3SwPNiZnZ0ll+VWRbdVq/RTsYmj"
    "K10/NypaFO3vOPpebDoV3dedXqk4uinaIlrud+rDLJnFsy+L2/nXslLN8GTz67rcLNV2p3TRdlrhF6u6wV8uGCNZHkcSCEAc"
    "QZYkJImjVnfqI350U3cPGzU7hSnmC12vu1Vb1tVd0faQuqjW9fYCRA8BMhAonV8iyJNa1M9Kv6AwZkphIrgkORkSzO9Ug6Ir"
    "WGjVNEaxIz1IiGRIEFIiWGBhbv0FERL1T4YXiBH6v4/sZanfcpPIreckBfYwrA7mlcpIBIwTDoHKXxUt+n1/XeyKVdnuX6SC"
    "gRA1vCA/x2/7UKqqfS36v7qM2/ElA8V2V8XsqmRw/6gbkuYWJPbTD3mv2m63xKB44UeHCeyfMlB0Xz4wNuRDmgWobmM68wEG"
    "qVggEPdoD7b26Yig+FZu3tqVpvlgCJpJQkON4UACwlJEOiCOiZyTgP8ROuAoTVAis94dGRFZYAdOI0lB+EDSkA1CcpqCDz0U"
    "wUvDbQphm4KPGMiptgdzKW8UP+oWZC+vKTglrM8xnhGggaU5G8CMXsHjPZVafDIk6leLMpLyfoTMKI2RHyYRX57ppgEC3L2U"
    "Bk6BF/AABBjeY5e5I4RGr3PqGAXOSZr3IWTCKKi06QznJXkgd+yvE/B6v9qo13sXSC834ePcAO/wwo9a/7mtcKZXCGHpm5gQ"
    "hPDTpO+E2rtH0oOZRmxZZ9ZIs7CDw/60iQ5rmuYYXeL8UfBzty3XZlUcENCF+H+OR/BAMzsJ0YEQBBPytH781HIfXKid7eqc"
    "NIeOQRa8B91LmtpL+tyt81Ol9K/9T9Ug2LqwGoiJnmMH8Q4beNKVnpK4XdK5OLnqHh/tHMrsy8mYXQWTbKrUM79y8BPeMJOx"
    "ByI3prkOSHM5OHtFsa3qxkSj8iFnZOo+zf8FPNb1jQ=="
)


def instructions():
    return _blob(_INSTRUCTIONS)


_TAGS = (
    "eNrtXVtP20gU/iujoEqwgmC7ubCs+hBSdhsttFGhi3YJDxP7JJnF9lj2GJpF/Pcd34KT2EmcG44zEoogM/Y5c75vzm1c96XE"
    "cP9Egx4xCSPUPNWxa6oDC2unf7Zbp3zQKf/rULN0XrrvmAi9eB8IdUpPWHfhhrq2Cp3SOf+CWmqndBwND4jDqD28JQZ8Bqx1"
    "sal502rSaAaf32JgtDEbBDcwnU/yb86n+6tIgwdPg4bRJWCyWzAssDFzbZiSQlSsR0KuqRbq863Xi80Es/+F9H1JH+vls9H3"
    "GlVdg98fe4sPLgwlomSRPWobmN0wm5j9YP7B8cGBVJbGhf3g5gyGOx1XkrpSMzbOrXo7tEI9G4waRL3F/dgEDTP8NuN3nWJ2"
    "Nm3ctk2fiAZ2MGsE3PTESxN3dfABYLYLo2ETGzC25uQlc6RuwH6KBLX6AVXQt3YT/WigaMyb/nr8PiQhdtsGx1kDO86Uerky"
    "kx7ERgnCFuTFFX32RqtVuVxL5stjG+ebKom23gGOBBT/4hpEI2y4Kk9kiWO7iBtJEJjClTQP8mEXXEfCMvPPieZQ1cG7zcox"
    "ZQ4X+EJxH5AvD00IZJTqjFhhtFjAo6QSxQH11PX/yjFfkmy+RqYYYHA1phW7xj8bfZigyXwiLc6GBNjbOlZhQHXfcG8ToYdd"
    "nf3lae7HAmku5AdpiN9efM4CdlY0A6N54pxg7s1lcxnMkw0RXn6DDUuH75hNouP4A2/2boNNqEbUd3UZlybY/eHf4DCwNbxy"
    "GKnOdhyBNHSFHYaUysB2VvIPf9wNcu0a0m2b/1ByR+3HlsmNofLcaOPJhScNtUwUykOHd6320fIZhhvs8GWp0TJZZaPESDPu"
    "GmkBPy17VtSQM1DGuxdXdITWy3354TMmumcSzVU9FcuXAdqv6Bd0yOg10XXiHGJN+8J1cg5N+nzISSBJR8d9YJ6o/6gJnC8O"
    "sMOjo6MPZ7WK5I+fRr+Nm2URyk6olELFX+dx0b8NSrxP5nimYgfyTMR0k20yhRlfZGTODS7zK2Uwfulk0sJTD/wIyOQTHTQA"
    "GxDfBogNYIieOZdRF5CDn4B/RRFGHEbEuYB0HuRt5DpQXgDjd3TmN8Bcay11gbRYYeALnCwMMreaDGLmOr4nmXWrqb+8ClVW"
    "DuqZPSm6/GmBymDWRvTumsnfTmXdsfT+uvU1n555qhAZ13RZ/51g38SiRF6gJtmhXPXC7fUSKrF1J6lTYgqWlU6tLwvyHfOh"
    "dDz78MU1sT084Zmkz4joGMZnCyeiSqOF/hGqwAkEdpR1yuFX/HJu74Dk56iHdQfCEcpn20TzVjm2SI4T0cHfZ/cx0wfnQIH2"
    "D+FEzPi9uy4LZo94rFKzR3yEX15HxtF5DctZRXqcZhFHwiv8W6nc6BOgnDhewBgZ2FeEk99hfBMGUxVJqZ1IMv+5laRz/+ef"
    "QEXfxP7H6zw7XxETnDxYu4hm9T4/5uAcMa7NBTcw2MMmtrA63rLGOraNOPXRmzG9cWPkFi9Ap89hFD6OT+HGtSgxWcObp7z1"
    "d6a8R6AE8k+ExubouAt6MMnTF32cGLd4yLF9vf1ICBpxjQidEJ9oi6Z55lB2ggUyJ535Pp1Ihzr/YTpO2QbPV56gTZ/HW8lr"
    "MmcsqnvNhLK0xDFQooKZ2fR4l4VOu4Xhd3A8hZSE49N1AZmw10OpSAlOrcvL7KIZmmdHONv59m5B/FZaBKXDNgCO1YsTQhc/"
    "n0lTOzO6fs5+mrERsVsYfyP6dncwF4hSH29ZAN1khcXGTfDNW8c28s4jjFfxzwLo+UA3KdGTH3OLJUG1auzprMVrgkaXV3lz"
    "a4LqWWpN4CkXf+4QBQrNqw6ypP6TIgr/aGM64BnbNR0zS8Urmjfb7jLUctVlqM3oMmwwnsyo7NdQM2+2ObBLgaS2RCAR3nhd"
    "3vj90Rf9mN3fwaIfU/BsvybKun0BWjRlCgiq6KZuupu6wFMIcUBEUbvtoraaq6K2KqqePa56qiLKFi/KVkUZVHyIRSuywK3I"
    "qsiTC//UQVV0MvbFV4vO8laL2qooarde1FZyVdRWRHpU5PSoIkLnfoTOimhPFHj3ivZEcSEWTeX9bSpXRMFTgB0sOlC5Oqmt"
    "iKJ260VtPVdFbV0UtUUuausiahYAQxE1i35uUxc9iSKCKnoShYdY9CT2tydRF0cG29nmmYrauihqt17UKrkqahWxL/cj/Cqi"
    "vC0AhqK8LXp5q4hKqPiuWHQwCghq4V6DpMx8SWqT/+q93lq8K2kPyndl117wq4gX/L7zC34zvt5LEa2Irbci5Fy1ImSR+RY9"
    "SZJ3LYzIE+MacSwdDxP+BxsRZvbzPfJy8fJ+WeT9Iu+P2C1aFQWMwuLMZ0+AFmc+u4+hOPPZwj8EyNKqkEWrYl2titf/ATcN"
    "CIs="
)


def tagFiles():
    return _json(_TAGS)
